### PR TITLE
Kill yourself

### PR DESCRIPTION
**Pull request by rbranson**
Please do it for us all. Ruby is like a celebrity with an image problem, and you just made it streak through the "I have a dream" speech.

### CODE REVIEW

**Comment by driftx** [comment]
+1

**Comment by dmitriy-kiriyenko** [comment]
-1.
Go ahead, guys. Evolution loves divergence.

**Comment by paulbellamy** [comment]
-1
Really? You encourage someone to commit suicide because you think they are making your favourite language look bad?

Can't imagine why "Ruby [has] an image problem"...

**Comment by jstrutz** [comment]
Thank you for your time; however we cannot fulfill your request that we kill ourselves at this time.  Please check back as we make progress.  We wish you the best of luck in your future endeavors.

**Pull request closed without merging**
